# Generated by Django 3.0.4 on 2020-04-26 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic_record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicrecord',
            old_name='chosen_topic_status',
            new_name='is_chosen',
        ),
        migrations.CreateModel(
            name='Topic2Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic_record.TopicRecord')),
            ],
        ),
        migrations.CreateModel(
            name='Topic2Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic_record.TopicRecord')),
            ],
        ),
    ]
