# Generated by Django 3.0.4 on 2020-04-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_record', '0002_auto_20200426_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic2student',
            old_name='teacher',
            new_name='student',
        ),
    ]
