# Generated by Django 3.0.4 on 2020-04-26 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phase.UserPhase', verbose_name='用户所处阶段'),
        ),
    ]
