# Generated by Django 3.0.4 on 2020-04-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200426_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='成绩'),
        ),
    ]
