# Generated by Django 3.0.4 on 2020-05-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200426_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memo',
            field=models.TextField(blank=True, default='', null=True, verbose_name='自我介绍'),
        ),
    ]
