# Generated by Django 3.0.4 on 2020-04-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnexPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annex_phase', models.CharField(max_length=100, verbose_name='文件所属类型')),
            ],
            options={
                'verbose_name': '文件类型',
                'verbose_name_plural': '文件类型',
            },
        ),
        migrations.CreateModel(
            name='UserPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phase', models.CharField(max_length=100, verbose_name='用户所处阶段名称')),
            ],
            options={
                'verbose_name': '用户阶段',
                'verbose_name_plural': '用户阶段',
            },
        ),
    ]
