# Generated by Django 3.0.4 on 2020-05-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback2student',
            old_name='teacher',
            new_name='student',
        ),
    ]
