# Generated by Django 3.0.4 on 2020-04-26 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic_record', '0001_initial'),
        ('phase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='fdfs', verbose_name='附件')),
                ('raw_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='原始文件名')),
                ('detail', models.TextField(default=' ', verbose_name='描述')),
                ('annex_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.AnnexPhase', verbose_name='文件类型')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_record.TopicRecord', verbose_name='题目')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
            },
        ),
    ]
